{% set version = '0.3.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-funr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/funr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/funr/funr_{{ version }}.tar.gz
  sha256: e998fa1d773804e990553be2d3d2712d3c826725c5df320fe48acfa45668b286

build:
  number: 1006
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('funr')"           # [not win]
    - "\"%R%\" -e \"library('funr')\""  # [win]

about:
  home: https://github.com/sahilseth/funr
  license: MIT
  summary: A small utility which wraps Rscript and provides access to all R functions from the
    shell.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: funr
# Title: Simple Utility Providing Terminal Access to all R Functions
# Description: A small utility which wraps Rscript and provides access to all R functions from the shell.
# Version: 0.3.2
# Authors@R: person("Sahil", "Seth", email = "me@sahilseth.com", role = c("aut", "cre"))
# License: MIT + file LICENSE
# LazyData: true
# Imports: utils
# URL: https://github.com/sahilseth/funr
# BugReports: https://github.com/sahilseth/funr/issues
# RoxygenNote: 5.0.1
# Suggests: testthat
# NeedsCompilation: no
# Packaged: 2016-04-19 02:43:43 UTC; root
# Author: Sahil Seth [aut, cre]
# Maintainer: Sahil Seth <me@sahilseth.com>
# Repository: CRAN
# Date/Publication: 2016-04-19 08:12:03
