travis:
  secure:
    BINSTAR_TOKEN: 1DxOjG/R0m7l9JDKwC+W0D+gErgiatt6taEURjaIemAlsQonn3AwaZBBCzQiZicO5tHsEA9zP49095qDasPwumKBttc4YlAmGOBG4onCbIl61Pby2bSTkVHuTIAuq6u8+lUH3Drnt7tuqjZd32Ylv8SO+YPzI3HoZGaD4wmSqmJZG47C5ST94ZGlHUTGazyLeAlsvUOG2SlyTMNnheEeSY+zOGu0vJ07h1nkbbrO1ol1oiWiE1X5YghCKuAKuL6OE5hrpKPuDOXtFQqVVTMgkJw9ExV8T/f/fKSFA/psB9AqFquwLQAttP7ZWSBzvp+IYS8e1JABp+EkubxR8VBGqBVfoGWK0dRTgbjp6WXDOvg7ktqRgfv9vzffUkEvFLENFBJzFrUgjZlvJHSfmok2sFYJHoEL92UEl+KasrmB5ZSs8cF44fTEnMqxA7Pa7gKqQ4d4++7q1xrxEQ3B5FMC93tppk/VMSNvANLPGEjXukiBTrV5cIaF0l7VklHbwpvueyS48mdsXvuq4HsM0Ktzq/G0beKnje+xg9QljClRhTVF39WLDN8OfflJWCFulnOIpGdtKDEo6+MC+H5V3QFGD5bqr5VQpTBXeD9uqEESiIxmbOVHwQdgsFRAC+OBxdm37wuqA99PlCXieQPkgBNa0ZFbVg/LHXZdWlohm/DdYvo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
